### PR TITLE
Major change

### PR DESCRIPTION
**Pull request by zipizap**
Well, where to start explaning this... a few days ago I've seen this gem and noticed a few things I would like to do differently... these were mostly personal-taste changes and not so much improvements or bugfixes... things like using ruby-2.0, documentation with yard, and certain code changes relating json parsing...

I'm an amateur programmer (I dont do it professionaly), and have limited experience with git, and none with tests... even so, as I had no more pretension than to make some personal changes and better understand this gems code, Ive forked it and started to change it... At some point, my enthusiasm lead me to accumulate many changes without properly documenting and separating them with git branches... (well, my git branches are a real mess...). Also, I'm aware that I've break some "standards" like renaming files from my_class.rb to MyClass.rb ( but it seems a so much better fit)...

Nonetheless, I think the code changes are relevant, and they constitute an updated and working version of the previous code. 

Most notorious changes are:
- 100% compatible with previous work
- Bitstampede::BitstampPublicApi (all API methods implemented)
- Bitstampede::BitstampPrivateApi (same methods as before)
- documented Client methods using yard docs
- all Client methods (both Public and Private) have working examples/\* 
- fixed net_http_persistent to reuse an already existing connection
- 

The not-so-perfect sides:
- my git mess: just see latest commit of branch "major_changes"
- tests are not updated/created, I didn't touch them... and those are important

So I send you this pull request, for you to check the changes out (already warned about my git mess)
I code as a hobby, for pleasure - I'm not a professional, although it crosses my mind from time to time -  so I would love to hear some sincere feedback from you :)

Paulo

### CODE REVIEW

**Comment by knewter** [comment]
Thanks for the Pull Request.  The features look very nice to have, and obviously supporting the new bitstamp api is important now that they don't require username and password (urk).

Having said that, I have a couple of requests before I'd feel comfortable merging this:
- Please rename the files to ruby standard naming conventions, which is snake_case, rather than BigCased or camelCased.  There's no reason to diverge from the standard naming the rest of the community uses.
- Please get the tests passing, and write new tests for any new functionality you added.  There should be 100% test coverage on the project.

I'm trying to keep this an excellent example of how one should build an API client.  Adding the persistent http connections is definitely a huge plus.  I just can't merge code that doesn't pass specs and add specs.

Thanks again for the contribution.  Once those changes are in place, I'll gladly merge it :)

**Comment by knewter** [comment]
closing this since it never got updated again...

**Comment by zipizap** [comment]
Never got the time to revisit this again...

**Comment by knewter** [comment]
No worries. Was just pruning my issue.

**Pull request closed without merging**
